# 인공지능개론 colab 실습
202334716 이예나

## 라이브러리 import

In [1]:
from sklearn.datasets import load_breast_cancer
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.neighbors import KNeighborsClassifier
import seaborn as sns

## csv 파일을 드라이브에서 가져오기

In [2]:
import numpy as np
import pandas as pd
import seaborn as sns
from sklearn.model_selection import train_test_split
import tensorflow as tf
from tensorflow import keras

df = pd.read_csv("/content/drive/MyDrive/Colab Notebooks/2025-1_AI/car_evaluation.csv", header=None)
df

0      1      2     3      4     5      6
0     vhigh  vhigh      2     2  small   low  unacc
1     vhigh  vhigh      2     2  small   med  unacc
2     vhigh  vhigh      2     2  small  high  unacc
3     vhigh  vhigh      2     2    med   low  unacc
4     vhigh  vhigh      2     2    med   med  unacc
...     ...    ...    ...   ...    ...   ...    ...
1723    low    low  5more  more    med   med   good
1724    low    low  5more  more    med  high  vgood
1725    low    low  5more  more    big   low  unacc
1726    low    low  5more  more    big   med   good
1727    low    low  5more  more    big  high  vgood

[1728 rows x 7 columns]

## 컬럼명 지정하기
> df.columns

In [3]:
df = pd.DataFrame(df)

# 컬럼명 지정
df.columns = ["buying", "maint", "doors", "persons", "lug_boot", "safety", "output"]

df

buying  maint  doors persons lug_boot safety output
0     vhigh  vhigh      2       2    small    low  unacc
1     vhigh  vhigh      2       2    small    med  unacc
2     vhigh  vhigh      2       2    small   high  unacc
3     vhigh  vhigh      2       2      med    low  unacc
4     vhigh  vhigh      2       2      med    med  unacc
...     ...    ...    ...     ...      ...    ...    ...
1723    low    low  5more    more      med    med   good
1724    low    low  5more    more      med   high  vgood
1725    low    low  5more    more      big    low  unacc
1726    low    low  5more    more      big    med   good
1727    low    low  5more    more      big   high  vgood

[1728 rows x 7 columns]

## columns 확인

In [4]:
df.columns

Index(['buying', 'maint', 'doors', 'persons', 'lug_boot', 'safety', 'output'], dtype='object')

## 결측치 확인
> isnull().sum()

In [5]:
df.isnull().sum()

buying      0
maint       0
doors       0
persons     0
lug_boot    0
safety      0
output      0
dtype: int64

## output column의 value count 확인

In [19]:
df['output'].value_counts()

output
2    1210
0     384
1      69
3      65
Name: count, dtype: int64

In [20]:
columns = ['buying', 'maint', 'doors', 'persons', 'lug_boot', 'safety','output']

## 라벨 인코딩(Label Encoding)
: 데이터프레임 df의 특정 열(columns 리스트에 있는 열들)을 정수로 변환하는 것

범주형 데이터(문자열)를 모델이 이해할 수 있도록 숫자로 변환하는 작업이다.

---

라벨 인코딩은 **순서가 없는** 범주형 데이터에는 적절하지 않다.

-> 그럴 땐 원-핫 인코딩(One-Hot Encoding) 을 사용하는 것이 더 적절

In [21]:
label_encoders = {}
for column in columns:
    label_encoders[column] = LabelEncoder()
    df[column] = label_encoders[column].fit_transform(df[column])

## output 컬럼 분리(y)

In [9]:
# 데이터와 타겟 분리
x = df.drop('output', axis=1).values
y = df['output'].values

In [10]:
x

array([[3, 3, 0, 0, 2, 1],
       [3, 3, 0, 0, 2, 2],
       [3, 3, 0, 0, 2, 0],
       ...,
       [1, 1, 3, 2, 0, 1],
       [1, 1, 3, 2, 0, 2],
       [1, 1, 3, 2, 0, 0]])

In [11]:
y

array([2, 2, 2, ..., 2, 1, 3])

## 데이터 표준화 및 트레인/테스트 데이터 분리

In [22]:
# 데이터 표준화
scaler = StandardScaler()
x = scaler.fit_transform(x)

# 트레인 / 테스트 분리
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=0)

## 배열(데이터)의 차원(행, 열 크기) 을 확인

> 출력 결과가 오른쪽과 같다면, (4, 2) (1, 2) (4,) (1,)

- x_train.shape = (4, 2) → 훈련 데이터 4개 샘플, 2개 특성

- x_test.shape = (1, 2) → 테스트 데이터 1개 샘플, 2개 특성

- y_train.shape = (4,) → 훈련 라벨 4개

- y_test.shape = (1,) → 테스트 라벨 1개

In [23]:
x_train.shape, x_test.shape, y_train.shape, y_test.shape

((1382, 6), (346, 6), (1382,), (346,))

## 머신러닝을 위한 라이브러리 import

In [14]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.neural_network import MLPClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix

## SVM(SVC) 모델 생성

In [24]:
from sklearn.svm import SVC

clf_svm = SVC(random_state=0)
clf_svm.fit(x_train, y_train) # 모델 학습

pred_svm = clf_svm.predict(x_test) # 테스트 데이터 예측

print("\n--- SVM Classifier ---")
print(accuracy_score(y_test, pred_svm)) # 정확도 출력
print(confusion_matrix(y_test, pred_svm)) # 혼동행렬 출력


--- SVM Classifier ---
0.9132947976878613
[[ 73   1   4   1]
 [  7   8   0   2]
 [ 12   0 228   0]
 [  3   0   0   7]]


## 로지스틱 회귀(LR) 모델 생성

In [16]:
clf_lr = LogisticRegression(random_state=0)
clf_lr.fit(x_train, y_train)

pred_lr = clf_lr.predict(x_test)

print ("\n--- Logistic Regression Classifier ---")
print (accuracy_score(y_test, pred_lr))
print (confusion_matrix(y_test, pred_lr))


--- Logistic Regression Classifier ---
0.6502890173410405
[[  9   0  67   3]
 [  1   0  16   0]
 [ 22   0 214   4]
 [  2   0   6   2]]


## 의사결정나무(Decision Tree) 모델 생성

In [17]:
clf_dt = DecisionTreeClassifier(random_state=0)
clf_dt.fit(x_train, y_train)

pred_dt = clf_dt.predict(x_test)

print ("\n--- Decision Tree Classifier ---")
print (accuracy_score(y_test, pred_dt))
print (confusion_matrix(y_test, pred_dt))


--- Decision Tree Classifier ---
0.9682080924855492
[[ 71   4   4   0]
 [  0  17   0   0]
 [  2   0 238   0]
 [  1   0   0   9]]


## 랜덤포레스트(RF) 모델 생성

In [25]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score
import pandas as pd
import warnings
warnings.filterwarnings('ignore') # 경고 메시지 무시

print ("\n--- Radom Forest ---")
rf_clf = RandomForestClassifier(random_state=0)
rf_clf.fit(x_train, y_train)
pred = rf_clf.predict(x_test)
print(accuracy_score(y_test,pred))
print (confusion_matrix(y_test, pred))


--- Radom Forest ---
0.9653179190751445
[[ 73   4   1   1]
 [  1  13   0   3]
 [  1   0 239   0]
 [  1   0   0   9]]
